[workspace]
resolver = "2"
members = ["contracts/noop_policy", "contracts/deny_policy"]

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT"
publish = false

[workspace.dependencies]
soroban-sdk = { version = "26.1.0" }
stellar-accounts = { git = "https://github.com/OpenZeppelin/stellar-contracts", rev = "1e513890ecf79833c9d6e7ef38a9358001c0b111" }

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
